services:
  app:
    build:
      context: ./app
    container_name: sparkcheck-app
    ports:
      - "5980:80"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    networks:
      - sparkcheck-network
    restart: unless-stopped

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: sparkcheck-db
    ports:
      - "127.0.0.1:1433:1433"
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - sparkcheck-network
    restart: unless-stopped
    entrypoint: ["/bin/bash", "/usr/src/app/init.sh"]

volumes:
  mssql-data:

networks:
  sparkcheck-network: