services:
  app:
    build:
      context: ./app
    container_name: sparkcheck-app
    ports:
      - "127.0.0.1:5980:80"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=dbSparkCheck;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;"
      SC_USE_ASTERISK: "${SC_USE_ASTERISK}"
      SC_OPENAI_KEY: "${SC_OPENAI_KEY}"
    networks:
      - sparkcheck-network
    restart: unless-stopped

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: sparkcheck-db
    ports:
      - "127.0.0.1:1433:1433"
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - sparkcheck-network
    restart: unless-stopped
    entrypoint: ["/bin/bash", "/usr/src/app/init.sh"]

  matcher:
    build:
      context: ./matcher
    container_name: sparkcheck-matcher
    command: uvicorn main:app --host 0.0.0.0 --port 9988
    ports:
      - "127.0.0.1:9988:9988"
    networks:
      - sparkcheck-network
    restart: unless-stopped
    depends_on:
      - db
    environment:
      SC_MATCHER_CONN: "mssql+pyodbc://sa:${SA_PASSWORD}@db:1433/dbSparkCheck?driver=ODBC+Driver+18+for+SQL+Server&TrustServerCertificate=yes"

  verification:
      build:
        context: ./verification
      container_name: sparkcheck-verification
      ports:
        - "127.0.0.1:9977:9977"
      volumes:
        - ./verification/asterisk/manager.conf:/etc/asterisk/manager.conf
        - ./verification/asterisk/extensions.conf:/etc/asterisk/extensions.conf
      networks:
        - sparkcheck-network
      restart: unless-stopped
      depends_on:
        - db
      environment:
        SC_USE_ASTERISK: "${SC_USE_ASTERISK}"
        SC_SIP_HOST: "${SC_SIP_HOST}"
        SC_SIP_PORT: "${SC_SIP_PORT}"
        SC_SIP_NUMBER: "${SC_SIP_NUMBER}"
        SC_SIP_USERNAME: "${SC_SIP_USERNAME}"
        SC_SIP_PASSWORD: "${SC_SIP_PASSWORD}"

volumes:
  mssql-data:

networks:
  sparkcheck-network: